package com.aws.springBootCRUD.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customer")
public class Customer implements Serializable {
    @DynamoDBHashKey(attributeName = "customerId")
    @DynamoDBAutoGeneratedKey
    private String customerId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int customerPhoneNumber;
    @DynamoDBAttribute
    private String emailAddress;
    @DynamoDBAttribute
    private Address address;
}
